-- --例題１ (p33)
-- SELECt * FROM employee;
-- --例題３（p34）
-- SELECT emp_name, sal from employee;
-- --例題4(p34)
-- SELECT emp_name, birthday, sal, sal*12 FROM employee;
-- --例題5（p35）
-- SELECT emp_name, birthday, sal, sal*12 AS 年収 FROM employee;
-- --例題６（p35）
-- SELECT emp_name, birthday, sal, sal*12, CAST(sal*12 AS int) AS 年収 FROM employee;
-- --例題７(p36)
-- SELECT emp_name, birthday, sal, (sal*12)::int AS 年収 FROM employee;
-- --例題１(p36)
-- SELECT '担当者' || emp_name || ' の誕生日は ' || birthday ||'です。 'AS 誕生日 FROM employee;
-- --例題１(p37)
-- SELECT emp_name, to_char(birthday, 'Day, Month DD, YYYY') FROM employee;
-- --例題２(p38)
-- SELECT emp_name, to_char(sal * 1000, '9G999G999D99') FROM employee;
-- --4.1.6
-- SELECT emp_name, birthday, sal, comm, sal + comm AS 収入 FROM employee;
-- --4.1.7　例題1(p41)
-- SELECT emp_name, birthday, sal, comm, sal + COALESCE(COMM, 0)  FROM employee;
-- --4.1.8 例題1(p42)
-- SELECT emp_name,
--         CASE gender
--             WHEN = 1 THEN  '男'
--                     ELSE  '女'
--         END AS 性別
--     FROM employee;
-- --例題5(p44)
-- SELECT 
--     emp_name,
--     birthday,
--     sal,
--     comm, 
--     sal + CASE WHEN comm IS NULL THEN 0 ELSE comm END
-- FROM employee;
--4.1.9　例題１
-- SELECT * FROM employee ORDER BY birthday DESC;
--4.1.9 例題２
--SELECT * FROM employee ORDER BY sal DESC;
--4.1.9 例題３
--SELECT * FROM employee ORDER BY gender, sal DESC;
--4.1.9 例題４
--SELECT emp_name, birthday, sal, comm, sal + comm  AS 月収 FROM employee ORDER BY 月収;
--4.1.10 例題１
--SELECT * FROM employee ORDER BY sal DESC LIMIT 3 OFFSET 1;
